### ISSUE TITLE
Autorisation pour l'utilisation de l'authentification CAS (CCSD)

### ISSUE THREAD

**Issue by Lubna93** [CCSDForge/HAL#26]
Bonjour, J'espère que vous allez bien. :)
Je développe une application pour l'Université Paul Valéry Montpellier qui nécessite l'utilisation de "Connexion par HAL". J'ai déjà préparé le code pour me connecter au CAS CCSD. Maintenant, il me faut simplement l'autorisation pour utiliser ce service.
Pourriez-vous m'indiquer comment obtenir officiellement cette autorisation ou les étapes à suivre ?
Merci beaucoup pour votre aide.

**Comment by Lubna93** [comment]
![Screenshot 2024-07-22 at 10 29 56](https://github.com/user-attachments/assets/9cbf091c-74a6-4333-883b-b4182628e13a)

**Comment by Lubna93** [comment]
![Screenshot 2024-07-22 at 10 29 56](https://github.com/user-attachments/assets/3bea6e2e-d58c-4024-91db-71abc91f5479)

**Comment by marmol** [comment]
Bonjour, 

Il nous faut l’intitulé du service, un contact avec adresse "permanente" a l’université, l'adresse du service (nom de machine +nom de domaine a autoriser ainsi que son adresse IP. 

Cordialement, 

----- Le 22 Juil 24, à 10:18, Lubna Altungi ***@***.***> a écrit : 

> Bonjour, J'espère que vous allez bien. :)
> Je développe une application pour l'Université Paul Valéry Montpellier qui
> nécessite l'utilisation de "Connexion par HAL". J'ai déjà préparé le code pour
> me connecter au CAS CCSD. Maintenant, il me faut simplement l'autorisation pour
> utiliser ce service.
> Pourriez-vous m'indiquer comment obtenir officiellement cette autorisation ou
> les étapes à suivre ?
> Merci beaucoup pour votre aide.

-- 
Bruno Marmol. 

Unité mixte de service CCSD 
Email: ***@***.*** - Tel: 06 84 76 06 83 
Inria.

**Comment by Lubna93** [comment]
Bonjour,

Merci beaucoup pour votre réponse rapide, vraiment apprécié.

Voici les informations demandées :
- **Intitulé du service :** Hébergement web pour b114.fr
- **Contact administrateur :** pf225689-ovh
- **Propriétaire :** 20395881
- **Adresse du service :**
    1. Nom de machine : b114.fr
    2. Nom de domaine : ch.b114.fr
    3. Serveurs DNS : ns102.ovh.net, dns102.ovh.net
    4. Adresses IP :
        217.182.137.148
        51.178.146.200
        10.30.90.1

PS : Ce domaine sera temporaire. Pour la production officielle, nous utiliserons un serveur de l'UPVM.

Cordialement,
Lubna

**Comment by Lubna93** [comment]
Bonjour,

Merci beaucoup pour votre réponse rapide. Je vais envoyer ces détails à l'adresse email hal.support@ccsd.cnrs.fr pour plus de sécurité.

Merci encore et passez une bonne journée ! :)
